apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: mohit682/node-app:latest
          imagePullPolicy: Always   # 👈 This forces Kubernetes to pull the image from Docker Hub
          ports:
            - containerPort: 3000
