name: Dev Branch CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test || echo "Tests failed but continuing"

      - name: Build Docker image
        run: |
          docker build -t mohit682/node-app:dev .

      - name: Push Docker image to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push mohit682/node-app:dev
